version: "3.9"

services:
  app:
    build: ./app/
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - subwayproject_default
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subway
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - subwayproject_default
  adminer:
    image: adminer
    ports:
      - "8888:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=subway
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      subwayproject_default:


volumes:
  db-data:

networks:
  subwayproject_default: